openapi: 3.0.1
info:
  title: Api do Microempreendedor
  version: v1
  description: |- 
    A api-mei é disponibilizado através do `HTTP REST` oferencendo as operações de 'Listar CNPJs', 'Consultar Certificados' e 'Consultar Certificados Específicos'.
    ### API Serpro - Plataforma de Habilitação  
    O contratante terá acesso a todas as informações relacionadas ao modelo de sustentação comercial e técnica dos serviços API por meio do portal de relacionamento com o cliente Minha Conta, onde as principais funcionalidades são detalhadas no tutorial Área do Cliente.
    
    Para informações de como se autenticar antes de consumir a API, por favor, consulte a documentação em [Autenticação](http://devserpro.github.io/apis/)  
    ### Códigos de Retorno não Tarifados 
    | Código de retorno | Resumido | Explicação |
    | ------|------|------|
    | 400 | Requisição inválida | O número de CPF/CNPJ informado não é válido. |
    | 500 | Erro no Servidor | Ocorreu algum erro no servidor.|
    ### Solicitando assinatura com Carimbo de Tempo
      Caso deseje que sua solicitação venha com uma assinatura de Carimbo de Tempo, basta incluir, no cabeçalho de sua requisição, a informação: &nbsp; *x-signature:1*. &nbsp; A assinatura será retornada no cabeçalho da resposta, com o nome: &nbsp; *stamp* .
    ### Verificando assinatura com Carimbo de Tempo
      Para verificar assinatura de carimbo de tempo, siga as instruções da documentação abaixo:     
    [Documentação - Verificação de Carimbo de Tempo](https://rawgit.com/devserpro/apis/master/_layouts/swagger-ui-master/dist/index.html?bearer=4e1a1858bdd584fdc077fb7d80f39283&url=https://rawgit.com/devserpro/apis/master/_layouts/swaggers/carimbo-tempo/swagger-timestampcheck-trial-bsa.json#!/default/post_check)
servers:
  - url: 'https://apigateway.serpro.gov.br/consulta-mei-trial/api'
    description: Trial
  - url: 'https://apigateway.serpro.gov.br/consulta-mei/api'
    description: Produção
security:
  - APIKEY: []
    OAuth2: []
    Authorization: []
externalDocs:
  description: "Detalhamento da API MEI"
  url: https://github.com/devserpro/apis/raw/master/portal-desenvolvedor/apis/documentos/Informacoes-MEI.pdf    
paths:
  '/v1/mei/cnpjs/{cpf}':
    get:
      tags:
        - MEI
      summary: Listar os CNPJs de um CPF
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      description: |-

        ## Exemplo
        #### Chamada
              [GET] https://apigateway.serpro.gov.br/consulta-mei-trial/api/v1/mei/cnpjs/71066868409
        #### Parâmetros de Entrada
            {
              "CPF": "71066868409" 
            }
        #### Retorno
            [
              { 
                "cnpj": "22025711000153",
                "situacao": "SUSPENSO"
              },
              {
                "cnpj": "22025711000154",
                "situacao": "ATIVO"
              }
            ]
      parameters:
        - name: cpf
          in: path
          description: Número do CPF do responsável
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Processamento ok
          headers:
            stamp:
              description: Carimbo de Tempo. Só aparecerá se o cabeçalho x-signature for igual a 1
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CNPJs'
              example:
                - cnpj: '22025711000153'
                  situacao: SUSPENSO
                - cnpj: '22025711000154'
                  situacao: ATIVO
        '400':
          description: Requisição com erro.
        '404':
          description: Nenhum registro encontrado.
        '500':
          description: Erro interno do servidor  

      operationId: https://apigateway.serpro.gov.br/consulta-mei-trial/api/v1/mei/cnpjs/71066868409
      externalDocs:
        description: "MEI para degustação"
        url: https://github.com/devserpro/apis/raw/master/portal-desenvolvedor/apis/documentos/MEI-Degustacao.pdf          
  '/v1/mei/certificado/{cpf}':
    get:
      tags:
        - MEI
      summary: Consultar Certificados Ativos de um CPF
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      description: |-

        ## Exemplo
        #### Chamada
              [GET] https://apigateway.serpro.gov.br/consulta-mei-trial/v1/mei/certificado/71066868409?ativo=true/ (traz apenas os CNPJs ativos) 
        #### Parâmetros de Entrada
            {
              "CPF": "71066868409"
            }      
        #### Retorno
            {
              "nomeEmpresarial": "DGKQWMX CHMIQAGH WXMVHU 71066868409",
              "nomeEmpresario": "",               
              "nomeFantasia": "DCW PHNQKXHU",
              "capitalSocial": 500000,
              "identidade": {
                "numero": "",
                "orgaoEmissor": "",
                "ufEmissor": "",
                "cpf": "71066868409"
              },
              "situacaoCadastral": "ATIVO",
              "dataSituacaoCadastral": "2015-03-11",
              "cnpj": "21025711000154",
              "nire": "32814140480",
              "enderecoComercial": {
                "cep": "71400050",
                "logradouro": "RUA OHMRWPQM KXMUVWMV",
                "numero": "171",
                "bairro": "SETOR O",
                "municipio": "CEILANDIA",
                "uf": "DF"
              },
              "dataInicioAtividades": "2015-03-11",
              "formaAtuacao": [
                "Em Local Fixo Fora da Loja"],
              "ocupacaoPrincipal": {
                "nome": "",
                "cnae": {
                  "codigo": 7439098,
                  "descricao": "Aluguel de carros importados para competição automobilística"
                }
              },
              "ocupacoesSecundarias": "[]",
              "numeroRecibo": "ME80700244",
              "numeroIdentificador": "71066868409",
              "dataEmissao": "2018-05-04"
            }
      parameters:
        - name: cpf
          in: path
          description: Número do CPF do responsável
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Processamento ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dadosCNPJs'
              example:
                nomeEmpresarial: DGKQWMX CHMIQAGH WXMVHU 71066868409
                nomeEmpresario: ''
                nomeFantasia: DCW PHNQKXHU
                capitalSocial: 500000
                identidade:
                  numero: ''
                  orgaoEmissor: ''
                  ufEmissor: ''
                  cpf: '71066868409'
                situacaoCadastral: ATIVO
                dataSituacaoCadastral: '2015-03-11'
                cnpj: '21025711000154'
                nire: '32814140480'
                enderecoComercial:
                  cep: '71400050'
                  logradouro: RUA OHMRWPQM KXMUVWMV
                  numero: '171'
                  bairro: SETOR O
                  municipio: CEILANDIA
                  uf: DF
                dataInicioAtividades: '2015-03-11'
                formaAtuacao:
                  - Em Local Fixo Fora da Loja
                ocupacaoPrincipal:
                  nome: ''
                  cnae:
                    codigo: 7439098
                    descricao: Aluguel de carros importados para competição automobilística
                ocupacoesSecundarias: '[]'
                numeroRecibo: ME80700244
                numeroIdentificador: '71066868409'
                dataEmissao: '2018-05-04'
        '400':
          description: Requisição com erro.
        '404':
          description: Nenhum registro encontrado.
        '500':
          description: Erro interno do servidor 
      operationId: https://apigateway.serpro.gov.br/consulta-mei-trial/v1/mei/certificado/71066868409?ativo=true/
      externalDocs:
        description: "Mei para degustação"
        url: https://github.com/devserpro/apis/raw/master/portal-desenvolvedor/apis/documentos/MEI-Degustacao.pdf          
  '/v1/mei/certificado/{cpf}/{cnpj}':
    get:
      tags:
        - MEI
      summary: Consultar Certificado Específico de um CPF
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      description: |-

        ## Exemplo
        #### Chamada
              [GET] https://apigateway.serpro.gov.br/consulta-mei-trial/v1/mei/certificado/71066868409/22025711000153
        #### Parâmetros de Entrada
            {
              "CPF": "71066868409",
              "CNPJ": "22025711000153"
            }
            
        #### Retorno
            {
              "nomeEmpresarial": "DGKQWMX CHMIQAGH WXMVHU 71066868409",
              "nomeEmpresario": "",               
              "nomeFantasia": "DCW PHNQKXHU",
              "capitalSocial": 30000,
              "identidade": {
                "numero": "",
                "orgaoEmissor": "",
                "ufEmissor": "",
                "cpf": "71066868409"
              },
              "situacaoCadastral": "SUSPENSO",
              "dataSituacaoCadastral": "2015-03-11",
              "cnpj": "22025711000153",
              "nire": "35814140440",
              "enderecoComercial": {
                "cep": "13400050",
                "logradouro": "RUA OHMRWPQM KXMUVWMV",
                "numero": "1031",
                "bairro": "CENTRO",
                "municipio": "PIRACICABA",
                "uf": "SP"
              },
              "dataInicioAtividades": "2015-03-11",
              "formaAtuacao": [
                "Em Local Fixo Fora da Loja",
              ],
              "ocupacaoPrincipal": {
                "nome": "",
                "cnae": {
                  "codigo": 7739099,
                  "descricao": "Aluguel de outras máquinas e equipamentos comerciais e industriais Não especificados anteriormente, sem operador"
                }
              },
              "ocupacoesSecundarias": " [ ] ",
              "NumeroRecibo": "ME80700244",
              "numeroIdentificador": "71066868409",
              "dataEmissao": "2018-06-04"
            }
      parameters:
        - name: cpf
          in: path
          description: Número do CPF do responsável
          required: true
          schema:
            type: string
        - name: cnpj
          in: path
          description: CNPJ associado ao responsável
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Processamento ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dadosCNPJs'
              example:
                nomeEmpresarial: DGKQWMX CHMIQAGH WXMVHU 71066868409
                nomeEmpresario: ''
                nomeFantasia: DCW PHNQKXHU
                capitalSocial: 30000
                identidade:
                  numero: ''
                  orgaoEmissor: ''
                  ufEmissor: ''
                  cpf: '71066868409'
                situacaoCadastral: SUSPENSO
                dataSituacaoCadastral: '2015-03-11'
                cnpj: '22025711000153'
                nire: '35814140440'
                enderecoComercial:
                  cep: '13400050'
                  logradouro: RUA OHMRWPQM KXMUVWMV
                  numero: '1031'
                  bairro: CENTRO
                  municipio: PIRACICABA
                  uf: SP
                dataInicioAtividades: '2015-03-11'
                formaAtuacao:
                  - Em Local Fixo Fora da Loja
                ocupacaoPrincipal:
                  nome: ''
                  cnae:
                    codigo: 7739099
                    descricao: 'Aluguel de outras máquinas e equipamentos comerciais'
                ocupacoesSecundarias: ' [ ] '
                NumeroRecibo: ME80700244
                numeroIdentificador: '71066868409'
                dataEmissao: '2018-06-04'
        '400':
          description: Requisição com erro.
        '404':
          description: Nenhum registro encontrado.
        '500':
          description: Erro interno do servidor  
      operationId: https://apigateway.serpro.gov.br/consulta-mei-trial/v1/mei/certificado/71066868409/22025711000153
      externalDocs:
        description: "MEI para degustação"
        url: https://github.com/devserpro/apis/raw/master/portal-desenvolvedor/apis/documentos/MEI-Degustacao.pdf           
  '/status':
    get:
      tags:
        - Status
      summary: Verifica status da API
      responses:
        '200':
          description: Serviço disponível
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
              example:
                lastUpdateAt: "2019-02-18T11:27:06-03:00"
        '500':
          description: Serviço indisponível
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
              example:
                lastUpdateAt: "2019-02-18T11:27:06-03:00" 
components:
  schemas:
    Status:
      type: object
      properties:
        lastUpdateAt:
          type: string
          format: date-time   
    CNPJs:
      properties:
        cnpj:
          type: string
        situacao:
          type: string
    dadosCNPJs:
      properties:
        nomeEmpresarial:
          type: string
        nomeEmpresario:
          type: string
        nomeFantasia:
          type: string
        capitalSocial:
          type: string
        identidade:
          type: object
          properties:
            numero:
              type: string
            orgaoEmissor:
              type: string
            ufEmissor:
              type: string
            cpf:
              type: string
        situacaoCadastral:
          type: string
        dataSituacaoCadastral:
          type: string
        cnpj:
          type: string
        nire:
          type: string
        enderecoComercial:
          type: object
          properties:
            cep:
              type: string
            logradouro:
              type: string
            numero:
              type: string
            bairro:
              type: string
            municipio:
              type: string
            uf:
              type: string
        dataInicioAtividades:
          type: string
        formaAtuacao:
          type: array
          items:
            type: string
        ocupacaoPrincipal:
          type: object
          properties:
            codigo:
              type: string
            cna:
              type: string
        ocupacoesSecundarias:
          type: object
          properties:
            codigo:
              type: string
            cna:
              type: string
        numeroRecibo:
          type: string
        numeroIdentificador:
          type: string
        dataEmissao:
          type: string
  securitySchemes:
    APIKEY:
      type: apiKey
      name: x-jwt-assertion
      in: header
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://apigateway.serpro.gov.br/token'
    Authorization:
      type: http
      description: Autenticação para ambiente trial
      scheme: bearer
